### ISSUE TITLE
Reconsider need for idempotent certificate registrations

### ISSUE THREAD

**Issue by tammersaleh** [18F/cf-domain-broker#5]
Currently, we take great pains to ensure that we can restart the certificate registration process without impacting the user (ie: cert registration is idempotent):

1. We re-implement the `Obtain()` entry point from the `lego` library.
1. We checkpoint the instance state (read, check, and write the instance info to DB) aggressively throughout.
1. We implement the virtual actor pattern across all managers to enable complete async behavior.

This adds a lot of complexity, which translates to difficulty in maintenance and increased time to debug issues.  Since issues in this broker's operation can result in real downtime for our end users, I'd like to explore ways we can reduce this complexity, and hopefully the time it would take to fix any such issues.

To that end:  What would be the expected impact on the end user if we didn't implement idempotent certificate registration?  Here's what I'm imagining, but I'm hoping this starts a discussion around the idea in the comments.

### Scenario 1:

**`Obtain()` is restarted _before_ the user sees the DNS instructions.**

1. :woman: User creates instance
1. Provisioning begins
1. ACME validation token (**A**) is generated
1. :boom: Broker is restarted
1. Provisioning restarts
1. New ACME validation token (**B**) is generated
1. :woman: User gets service status and sees instructions to update DNS with `TXT` record including **B**
1. :woman: User updates DNS
1. Broker verifies DNS
1. ACME provisioning proceeds as normal

I _believe_ this is pretty straight forward -- the user never notices.  I also wouldn't bet on this being a more likely path.  The bigger issue is...

### Scenario 2:

**`Obtain()` is restarted _after_ the user sees the DNS instructions.**

1. :woman: User creates instance
1. Provisioning begins
1. ACME validation token (**A**) is generated
1. :woman: User gets service status and sees instructions to update DNS with `TXT` record including **B**
1. :boom: Broker is restarted
1. Provisioning restarts
1. New ACME validation token (**B**) is generated
1. :woman: User updates DNS
1. Broker fails to verify DNS :no_good:
1. ACME provisioning stalls

Either one of two paths would then happen:

1. User gets status on instance, and we can report that there _is_ a `TXT` record, but that it doesn't match the expected token (**B**).  We can explain that this might be due to a restart on our end.
1. User doesn't bother checking the instance status, 24hrs pass, and we kill the instance entirely.

This isn't great by any means, but it's also not catastrophic.

### Thoughts?

Are there other scenarios I'm not considering?

Are there other impacts in the above scenarios?

What's even the likelihood we'll hit either of these?  (maybe we'll be deploying somewhat often, but we won't be provisioning new certs that frequently)

How much could we mitigate the impact on the user via documentation, clear error messages and our own support time?

How savvy are the users who'll be provisioning instances of this service?  Is it primarily Federalist?  If so, can we reach out to educate them of this issue beforehand?

**Thanks for reading all of the above, and thanks in advance for any thoughts and ideas you can contribute below.  I'll update the above with any new information from the comments.**

**Comment by mxplusb** [comment]
Scenario 1 is almost completely unlikely to happen because the validation token is received and then immediately handed to the user, I'm not sure that's perceivable outside a debugger or log message. Scenario 2 is what the idempotent code base plans for. 

Here's a likely situation:

1. User creates instance.
1. Provisioning begins.
1. An ACME order is placed, the validation token is generated and received.
1. The user sees the validation, copies the value, and then files a support ticket with their IT department.
1. Their IT department sees the ticket, hopefully before the 24 hour window expires.
1. The IT department copies the value in the ticket, then creates the DNS record, assuming with the right value.
1. The broker eventually resolves the DNS record, then continues on with the process.

The challenge here is the human process required to verify the record, not the technical. There are multiple layers of process involved, and while Federalist is likely the largest user, they are not the only one, and ensuring whatever software pattern you choose needs to account for multiple layers of at-human-speed process.

The original broker went with DNS-01, and we couldn't find a reasonable alternative, at the time, to the initial issuance hurdle. There are plenty of examples of automated certificate issuance with `certbot`, `cfssl` (Cloudflare's version of LE), and so many other tools - it's not the automated issuance which is the problem, it's the human factor. If there's a better path forward than DNS-01, it's likely worth exploring.
